# Simple test commands without race detection
test-simple: ## Run tests without race detection
	@echo "Running tests..."
	go work sync
	cd packages/product-service && go test -v ./...
	cd packages/gateway-service && go test -v ./...
	cd packages/shared && go test -v ./...

test-coverage-simple: ## Run tests with coverage (no race)
	@echo "Running tests with coverage..."
	go work sync
	cd packages/product-service && go test -v -coverprofile=coverage.out ./...
	cd packages/gateway-service && go test -v -coverprofile=coverage.out ./...
	cd packages/shared && go test -v -coverprofile=coverage.out ./...
