// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	Price         float64     `json:"price"`
	Currency      string      `json:"currency"`
	StockQuantity int32       `json:"stock_quantity"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}
