// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, description, price, currency, stock_quantity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, price, currency, stock_quantity, created_at, updated_at
`

type CreateProductParams struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	Price         float64     `json:"price"`
	Currency      string      `json:"currency"`
	StockQuantity int32       `json:"stock_quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.StockQuantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const findProductWithStockInfo = `-- name: FindProductWithStockInfo :one
SELECT 
  p.id                AS product_id,
  p.name              AS product_name,
  p.description       AS product_description,
  p.price             AS product_price,
  p.currency          AS product_currency,
  p.stock_quantity    AS product_stock_quantity,
  p.created_at        AS product_created_at,
  p.updated_at        AS product_updated_at
FROM products p
WHERE p.id = $1
`

type FindProductWithStockInfoRow struct {
	ProductID            int64       `json:"product_id"`
	ProductName          string      `json:"product_name"`
	ProductDescription   pgtype.Text `json:"product_description"`
	ProductPrice         float64     `json:"product_price"`
	ProductCurrency      string      `json:"product_currency"`
	ProductStockQuantity int32       `json:"product_stock_quantity"`
	ProductCreatedAt     time.Time   `json:"product_created_at"`
	ProductUpdatedAt     time.Time   `json:"product_updated_at"`
}

func (q *Queries) FindProductWithStockInfo(ctx context.Context, id int64) (FindProductWithStockInfoRow, error) {
	row := q.db.QueryRow(ctx, findProductWithStockInfo, id)
	var i FindProductWithStockInfoRow
	err := row.Scan(
		&i.ProductID,
		&i.ProductName,
		&i.ProductDescription,
		&i.ProductPrice,
		&i.ProductCurrency,
		&i.ProductStockQuantity,
		&i.ProductCreatedAt,
		&i.ProductUpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, currency, stock_quantity, created_at, updated_at FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.StockQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, currency, stock_quantity, created_at, updated_at FROM products
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.StockQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
